### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by bcherny**
Hey, thanks for the useful package @ungoldman! I added TypeScript typings for your code, so TypeScript/Flow/Reason users can use this package too.

Happy holidays!

### CODE REVIEW

**Comment by ungoldman** [comment]
Hi @bcherny! I'm glad you found this to be useful. I wrote this several years ago when I was still working for Esri. I no longer have admin access to this repository, but @dmfenton or @jgravois may be able to review your pull request.

🖖

**Comment by jgravois** [comment]
> @dmfenton or @jgravois may be able to review your pull request.

certainly. thanks for the contribution @bcherny! i'll take a closer look in the next couple days.

**Comment by jgravois** [comment]
prior relevant discussion: https://github.com/Esri/terraformer/issues/305

**Comment by jgravois** [comment]
tagged as `v1.1.2`. thank you @bcherny!

@ungoldman can you either `npm publish` or give me 🗝 s when you have a minute my fine squire?

**Comment by ungoldman** [comment]
@jgravois I removed myself as an owner when I left Esri. You can find the current owners of a package as follows:

```
~ $ npm owner ls esri-extent
chelm <christopher.helm@gmail.com>
dmfenton <dfenton@esri.com>
```

**Comment by jgravois** [comment]
and here i am, going to websites to see who published last like a sucka. 😄

**Pull request merged**
